name: Deploy SMTPLITE to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy smtplite files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_KEY }}
          port: 32123
          source: "server.js,smtp/,config/,utils/,logs/,README.md,LICENSE"
          target: "/home/rootr/projects/smtplite/"
          strip_components: 0

      - name: Restart smtplite.service on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_KEY }}
          port: 32123
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart smtplite.service
            sudo systemctl status smtplite.service --no-pager
